import os
from jira import JIRA
from dotenv import load_dotenv

# Load environment variables from the .env file
# This prevents sensitive data (API tokens, emails) from being exposed in the code
load_dotenv()

# Retrieve credentials and configuration from environment variables
JIRA_URL = os.getenv("JIRA_URL")
JIRA_EMAIL = os.getenv("JIRA_EMAIL")
JIRA_TOKEN = os.getenv("JIRA_TOKEN")
PROJECT_KEY = os.getenv("JIRA_PROJECT_KEY")

def create_jira_task(summary, description):
    """
    Connects to the Jira Cloud instance and creates a new Task.
    
    Args:
        summary (str): The title of the Jira ticket.
        description (str): The detailed body of the ticket.
    """
    print("🔄 Connecting to Jira Cloud...")

    try:
        # Establish connection using Basic Authentication (Email + API Token)
        # Note: Passwords are deprecated for Jira Cloud, API Token is required.
        jira = JIRA(server=JIRA_URL, basic_auth=(JIRA_EMAIL, JIRA_TOKEN))

        # Define the payload for the new issue
        issue_dict = {
            'project': {'key': PROJECT_KEY},
            'summary': summary,
            'description': description,
            'issuetype': {'name': 'Task'}, # Can be changed to 'Story', 'Bug', or 'Epic'
        }

        # Send the request to Jira API to create the issue
        new_issue = jira.create_issue(fields=issue_dict)

        print(f"✅ Ticket Created Successfully: {new_issue.key}")
        print(f"🔗 Link: {JIRA_URL}/browse/{new_issue.key}")

    except Exception as e:
        print(f"❌ Failed to create Jira ticket. Error: {e}")

if __name__ == "__main__":
    # Example usage: intended to be called when a new project is initialized
    task_title = "Automated Project Setup Review"
    task_desc = "This task was automatically generated by the Python Project Automation tool. Please review the folder structure."
    
    create_jira_task(task_title, task_desc)