import os
import sys

# Try to import the Jira integration module.
# We use a try-except block to implement "Graceful Degradation":
# if the Jira module is missing, the script will still create folders.
try:
    from jira_integration import create_jira_task
    JIRA_AVAILABLE = True
except ImportError:
    JIRA_AVAILABLE = False
    print("⚠️  Warning: 'jira_integration.py' not found or dependencies missing. Jira task creation will be skipped.")

def create_project_structure(project_name):
    """
    Scaffolds a new project directory structure and triggers
    remote task creation on Jira.
    
    Args:
        project_name (str): The name of the project/service to initialize.
    """
    output_dir = "generated_projects"
    
    # Crea la cartella contenitore se non esiste
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"📁 Created output directory: {output_dir}")

    base_path = os.path.join(output_dir, project_name)
    
    # Standard list of directories for a clean software architecture
    folders = [
        "docs",           # Documentation and ADRs
        "src",            # Source code
        "tests",          # Unit and integration tests
        "scripts",        # DevOps/Utility scripts
        "design"          # UI/UX assets
    ]
    
    print(f"🚀 Initializing project infrastructure: {project_name}...")

    # --- Step 1: Local Folder Creation ---
    try:
        # Create directories
        for folder in folders:
            path = os.path.join(base_path, folder)
            os.makedirs(path, exist_ok=True)
            print(f"   📂 Created directory: {path}")

        # Create a default README.md
        readme_path = f"{base_path}/README.md"
        if not os.path.exists(readme_path):
            with open(readme_path, "w") as f:
                f.write(f"# {project_name}\n\nProject initialized automatically via Automation Tool.")
            print(f"   📄 Created file: README.md")
        
        print(f"✅ Local scaffolding completed for '{project_name}'.")

    except OSError as e:
        print(f"❌ Critical Error: Could not create directories. {e}")
        return # Stop execution if file system operations fail

    # --- Step 2: Remote Jira Integration ---
    if JIRA_AVAILABLE:
        print("\n--- 🔗 Starting Jira Integration ---")
        
        # Dynamic content for the Jira Ticket
        ticket_summary = f"[Setup] Initialize infrastructure for {project_name}"
        ticket_description = (
            f"Automated task generated by the Project Automation Tool.\n\n"
            f"**Objective:**\n"
            f"A new service named '{project_name}' has been scaffolded locally.\n"
            f"Please verify the folder structure and push the initial commit to the remote repository."
        )
        
        # Call the external module function
        create_jira_task(ticket_summary, ticket_description)

if __name__ == "__main__":
    # Ensure a project name is provided via command line arguments
    if len(sys.argv) > 1:
        project_name_input = sys.argv[1]
        create_project_structure(project_name_input)
    else:
        print("❌ Error: Missing argument.")
        print("Usage: python3 setup_project.py <ProjectName>")